# Gunakan versi syntax docker-compose yang modern
version: '3.8'
# Beri nama proyek agar container tidak memiliki nama acak
name: mawarops-pipeline

# --- DEFINISI JARINGAN BARU DI SINI ---
networks:
  # Kita buat jaringan baru bernama 'mawarops-net'
  mawarops-net:
    driver: bridge # Tipe jaringan standar

# Definisikan semua service yang akan kita jalankan
services:

  # Service untuk menyajikan data dan hasil model
  data_service:
    build: .
    container_name: mawarops_data_service
    command: python -m scrip.data_service
    ports:
      - "8003:8003"
    volumes:
      - ./csv/cleaned_titles.csv:/app/csv/cleaned_titles.csv:ro
      - ./bertopic_model.pkl:/app/bertopic_model.pkl:ro
    # Hubungkan service ini ke jaringan kustom kita
    networks:
      - mawarops-net

  # Service untuk melatih model
  topic_modeling_service:
    build: .
    container_name: mawarops_topic_modeling_service
    command: python -m scrip.topic_modeling_service
    ports:
      - "8004:8004"
    volumes:
      - ./csv/cleaned_titles.csv:/app/csv/cleaned_titles.csv:ro
      - ./csv:/app/csv
      - ./:/app
    # Hubungkan service ini ke jaringan kustom kita
    networks:
      - mawarops-net

  # Service untuk preprocessing
  preprocessing_service:
    build: .
    container_name: mawarops_preprocessing_service
    command: python -m scrip.preprocessing_service
    ports:
      - "8002:8002"
    volumes:
      - ./csv:/app/csv
    # Hubungkan service ini ke jaringan kustom kita
    networks:
      - mawarops-net

  # Service untuk scraping
  scraping_service:
    build: .
    container_name: mawarops_scraping_service
    command: python -m scrip.scraping_service
    ports:
      - "8001:8001"
    volumes:
      - ./csv:/app/csv
    # Hubungkan service ini ke jaringan kustom kita
    networks:
      - mawarops-net

  # --- Monitoring Stack ---
  prometheus:
    image: prom/prometheus
    container_name: mawarops_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    # Hubungkan Prometheus ke jaringan yang sama agar bisa "melihat" service lain
    networks:
      - mawarops-net

  grafana:
    image: grafana/grafana
    container_name: mawarops_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    # Hubungkan Grafana ke jaringan yang sama
    networks:
      - mawarops-net

# Definisikan volume persisten untuk data Grafana
volumes:
  grafana-data: