# -*- coding: utf-8 -*-
"""topic_modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIactENSGK3prhXo55XiFtlQdlAYkj0j
"""

pip install bertopic scikit-learn pandas joblib

import pandas as pd
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import joblib

def train_topic_model(texts, model_path="bertopic_model.pkl"):
    """
    Latih model BERTopic pada list teks (judul atau abstrak).
    """
    # Inisialisasi model
    topic_model = BERTopic()

    # Training model
    topics, probs = topic_model.fit_transform(texts)

    # Simpan model
    joblib.dump(topic_model, model_path)
    print(f"Model BERTopic disimpan di {model_path}")

    return topic_model, topics, probs

def evaluate_topic_model(model):
    """
    Evaluasi BERTopic menggunakan coherence score internal.
    """
    score = model.get_coherence()
    print(f"Coherence Score: {score:.4f}")
    return score

def load_data_from_csv(csv_path='csv/cleaned_titles.csv'):
    """
    Load dan ambil teks dari file CSV hasil scraping.
    """
    df = pd.read_csv(csv_path)
    if 'Original Title' not in df.columns:
        raise ValueError("Kolom 'Original Title' tidak ditemukan.")
    return df['Original Title'].tolist()